### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by wanghaisheng** [dongweiming/r#1]
osx 10.10.5
python 2.7.7

```
(venv)➜ /Users/wanghaisheng/workspace/r git:(master) ✗>pip install -r requirement.txt
You are using pip version 6.0.6, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting Flask==0.10.1 (from -r requirement.txt (line 1))
  Using cached Flask-0.10.1.tar.gz
Collecting Flask-Mako==0.3 (from -r requirement.txt (line 2))
  Using cached Flask-Mako-0.3.tar.gz
Collecting Flask-SQLAlchemy==2.0 (from -r requirement.txt (line 3))
  Using cached Flask-SQLAlchemy-2.0.tar.gz
Collecting Jinja2==2.8 (from -r requirement.txt (line 4))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting python-magic==0.4.3 (from -r requirement.txt (line 5))
  Using cached python-magic-0.4.3.tar.gz
Collecting Mako==1.0.1 (from -r requirement.txt (line 6))
  Using cached Mako-1.0.1.tar.gz
Collecting MarkupSafe==0.23 (from -r requirement.txt (line 7))
  Using cached MarkupSafe-0.23.tar.gz
Collecting Pillow==2.9.0 (from -r requirement.txt (line 8))
  Using cached Pillow-2.9.0-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting MySQL-python==1.2.5 (from -r requirement.txt (line 9))
  Using cached MySQL-python-1.2.5.zip
    sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/var/folders/gt/qwrq183s2js2lwxbd18b4sw40000gn/T/pip-build-1EToKa/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    Complete output from command python setup.py egg_info:
    sh: mysql_config: command not found

    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/var/folders/gt/qwrq183s2js2lwxbd18b4sw40000gn/T/pip-build-1EToKa/MySQL-python/setup.py", line 17, in <module>

        metadata, options = get_config()

      File "setup_posix.py", line 43, in get_config

        libs = mysql_config("libs_r")

      File "setup_posix.py", line 25, in mysql_config

        raise EnvironmentError("%s not found" % (mysql_config.path,))

    EnvironmentError: mysql_config not found

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /var/folders/gt/qwrq183s2js2lwxbd18b4sw40000gn/T/pip-build-1EToKa/MySQL-python
```

**Comment by dongweiming** [comment]
@wanghaisheng 这个是你的系统没有安装mysql的依赖 可以参考

http://stackoverflow.com/questions/5178292/pip-install-mysql-python-fails-with-environmenterror-mysql-config-not-found

或者 

http://stackoverflow.com/questions/25459386/mac-os-x-environmenterror-mysql-config-not-found
